home:
  path: /
  controller: App\Controller\HomeController::index

upload:
  path: /upload
  controller: App\Controller\UploadController::upload

gallery:
  path: /gallery
  controller: App\Controller\GalleryController

search:
  path: /search
  controller: App\Controller\SearcherController

searchSubmit:
  path: /searchSubmit
  controller: App\Controller\SearcherController::searchSubmit
