home:
  path: /
  controller: App\Controller\HomeController::index

upload:
  path: /upload
  controller: App\Controller\UploadController::upload

gallery:
  path: /gallery
  controller: App\Controller\GalleryController
